# Generated by Django 5.2.4 on 2025-07-19 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='enrolled_programs',
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_info',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='healthprogram',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.healthprogram')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='programs',
            field=models.ManyToManyField(through='core.Enrollment', to='core.healthprogram'),
        ),
    ]
